sudo: false
language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '6'
  - '4'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn run validate
after_script:
  - yarn run codecov
cache: yarn
