sudo: false
language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '6'
  - '4'
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run validate
after_script:
  - npm run codecov
cache:
  directories:
    - node_modules
